import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>MovieApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Peliculas</h1>
        <Link href={'/movies/5'} key={5}>
          Pelicula 1
        </Link>
      </div>
    </div>
  );
}
